name: nilaway
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  nilaway:
    name: nilaway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5 # v5.0.1 https://github.com/actions/checkout/releases/tag/v5.0.1
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0 https://github.com/actions/setup-go/releases/tag/v6.1.0
        with:
          go-version: 1.25.x
      - name: install nilaway
        run: go install go.uber.org/nilaway/cmd/nilaway@latest
      - name: run nilaway
        run: nilaway ./...
